// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cbwvubvjtjhkpnxwxqbf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNid3Z1YnZqdGpoa3BueHd4cWJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0ODI1ODgsImV4cCI6MjA3MTA1ODU4OH0.2_q7p2fsTtV1DVWnj0VyDiFD6ZEBG916S7qVOZX4Jkk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});